mujoco_server:
  ros__parameters:
    MujocoPlugins:
      names:
        - mujoco_ros2_control
      mujoco_ros2_control:
        type: mujoco_ros2_control::MujocoRos2ControlPlugin
        hardware:
          type: mujoco_ros_control/RobotHW
          control_period: 0.001
        params:
          namespace: ""
          robot_description_node: "robot_state_publisher"
          robot_description: "robot_description"

controller_manager:
    ros__parameters:
      update_rate: 1000
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
      franka_robot_model_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotModelBroadcaster
      joint_velocity_controller:
        type: alberto_controllers/panda/JointVelocityController
      joint_impedance_controller:
        type: alberto_controllers/panda/JointImpedanceController

franka_robot_state_broadcaster:
  ros__parameters:
    arm_id: panda
    frequency: 60
    
franka_robot_model_broadcaster:
  ros__parameters:
    arm_id: panda
    frequency: 60

joint_velocity_controller:
  ros__parameters:
    arm_id: panda
    command_topic: /joint_velocities

joint_impedance_controller:
  ros__parameters:
    command_topic: /joint_velocities
    arm_id: panda
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5


